name: Lint Checks for Pull Requests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Black Lint
        uses: psf/black@stable
        with:
          options: "--line-length 95"
