name: Go Test on Pull Requests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
